# ECHELON FORM AND ROW REDUCED FORM

###  Row Reduced Echelon Form

we use the symbolic package that compute the row reduce echelon form  

In [1]:
# import sympy  
import sympy as sym
  
AS = sym.Matrix([[1, 2, 2, 3, 1, 0, 0], [2, 4, 1, 3, 0,1,0], [3, 6, 1, 4,0,0,1]])  
print("Matrix : {} ".format(AS)) 
   
# Use sympy.rref() method  
AS_rref = AS.rref()   
      
print("The Row echelon form of matrix M and the pivot columns : {}".format(AS_rref))   


Matrix : Matrix([[1, 2, 2, 3, 1, 0, 0], [2, 4, 1, 3, 0, 1, 0], [3, 6, 1, 4, 0, 0, 1]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 2, 0, 1, 0, -1,  1],
[0, 0, 1, 1, 0,  3, -2],
[0, 0, 0, 0, 1, -5,  3]]), (0, 2, 4))


we construct a function with in Input a Matrix of size m x n and that give in output the echelon form. The permutation is performed in order to have a stable algorithm using the technique of partial pivoting.

In [2]:
import numpy as np
  
A = np.array([[1, 2, 2, 3], [2, 4, 1, 3], [3, 6, 1, 4]]) 



In [3]:
def ef_withpivot(A): # the number of column is greater or equal the number of rows
    U = np.copy(A) # copy the matrix A in U 
    (m,n) = A.shape
    j = 0 # index related to the column

    for i in range(0,m): 
        ech = 1

        while (ech == 1) & (j < n):
          # find the pivotal index, maximum element in the column j FOR STABILITY REASONS
          indm = np.argmax(abs(U[i:m, j])) 
          indm = indm + i

         # perform the permutation to work well we should change != 0 with an absolute value less then a constant very small 
          if (indm != i) & (abs(U[indm,j]) > 1e-15): 
             U[ [i, indm],:] = U[[indm, i],:]
          if ( abs( U[i,j] ) > 1e-15):
             M = U[i+1:m, j]/ U[i, j] # vector because we do elimination of all the row below the pivotal one
                # in numpy array there is no difference row vectors or column vectors
                # np.outer to perform the outer product
             U[i+1 : m, j+1 : n] = U[i+1 : m, j+1 : n] - np.outer(M, U[i, j+1 : n]) 
             U[i+1 : m, j]=0
             j = j+1
             ech = 0
          else:
            j = j+1
            ech = 1      
    return(U)    



In [4]:
A = np.array([  [1., 2., 2., 3.], 
                [2, 4, 1, 3], 
                [3, 6, 1, 4]])
U = ef_withpivot(A)
print(U)


[[3.00000000e+00 6.00000000e+00 1.00000000e+00 4.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.66666667e+00 1.66666667e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.11022302e-16]]


## Exercise ECHELON FORM
Use the function of sympy sp.rref to compute the row reduced form of the matrix in the exercise 4.2.1  on page 178 of the book of Carl Meyer and find the  spanning sets for all the four fundamental subspaces


In [6]:
A_ex = np.array([  [1., 2., 1., 1., 5.], 
                [-2., -4., 0., 4., -2.], 
                [1., 2., 2., 4., 9.]]) 

print("Ex. page 178 4.2.1, \n Matrix A= \n{}".format(A_ex))
print("\n\n")   

U_solEx = ef_withpivot(A_ex)
print("Echelon form: \n Matrix A=\n {}".format(U_solEx))

Ex. page 178 4.2.1, 
 Matrix A= 
[[ 1.  2.  1.  1.  5.]
 [-2. -4.  0.  4. -2.]
 [ 1.  2.  2.  4.  9.]]



Echelon form: 
 Matrix A=
 [[-2. -4.  0.  4. -2.]
 [ 0.  0.  2.  6.  8.]
 [ 0.  0.  0.  0.  0.]]


we construct a function with in Input a Matrix of size m x n and that give in output the row reduced echelon form echelon form. The permutation is performed in order to have a stable algorithm using the technique of partial pivoting.

In [12]:
def rref_withpivot(A):
    U = np.copy(A)
    (m,n) = A.shape
    P = np.eye(m) 
    j = 0
    for i in range(0,m): 
        ech = 1

        while (ech == 1) & (j < n): 
          indm = np.argmax(abs ( U[i:m,j] ))  # we consider the portion of rows from the pivot (at index i to m)
          indm = indm + i

          if (indm != i) & (abs(U[indm,j]) > 1e-15): # perform the permutation
             U[ [i, indm],:]=U[[indm,i],:] 
             P[ [i, indm],:]=P[[indm,i],:] 

          if ( abs(U[i,j]) > 1e-15):
             M = U[i+1:m,j] / U[i,j]
             U[i+1:m, j+1:n]=U[i+1:m, j+1:n] - np.outer(M, U[i,j+1:n])
             U[i+1:m,j] = 0           
             U[i,j:n] = U[i,j:n] / U[i,j]   # the pivotal element should be 1    

             if i > 0 :
               M= U[0:i,j]/U[i,j]
               U[0:(i),j:n]=U[0:i,j:n]-np.outer(M,U[i,j:n])     
             j=j+1
             ech=0
             
          else:
            j=j+1
            ech=1
            
    return(U,P)    




In [10]:
A = np.array([[1., 2., 2., 3., 1., 0, 0], [2, 4, 1, 3, 0,1,0], [3, 6, 1, 4,0,0,1]]) 
(U,P)=rref_withpivot(A)
print(U[0:3,0:4])
print(U[0:3,4:7])

[[1.00000000e+00 2.00000000e+00 0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.11022302e-16]]
[[ 0. -1.  1.]
 [ 0.  3. -2.]
 [ 1. -5.  3.]]


In [7]:
B = np.random.rand(3,3)
I = np.eye(3)
A = np.block([B,I]) # to define a matrix using its blocks

In [13]:
A

array([[0.20525418, 0.89989087, 0.00735674, 1.        , 0.        ,
        0.        ],
       [0.43793334, 0.03461284, 0.23398477, 0.        , 1.        ,
        0.        ],
       [0.89786276, 0.26621773, 0.20960834, 0.        , 0.        ,
        1.        ]])

In [13]:
m = 3
n = 3
(U,P)=rref_withpivot(A)
print(U[0:m,0:n])
print(U[0:m,n:m+n])
X=U[0:m,n:m+n]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 3.44577423 -3.13344017  1.8992108 ]
 [-1.27575983  0.0860571   2.08001048]
 [-0.20667225  2.71656853 -3.44524916]]


In [19]:
np.dot(B,X)

array([[ 1.00000000e+00,  7.91570701e-17, -1.18594389e-17],
       [-2.37339025e-18,  1.00000000e+00, -9.03939619e-17],
       [-6.75195678e-17, -7.32602440e-17,  1.00000000e+00]])

In [20]:
np.dot(X,B)

array([[ 1.00000000e+00, -1.76844294e-16, -4.67934045e-17],
       [ 4.77886006e-18,  1.00000000e+00,  1.37385810e-17],
       [ 6.90011246e-17, -1.03533326e-17,  1.00000000e+00]])

Exercise:  use the function rref_withpivot to compute the row reduced form of the matrix in the exercise 4.2.1  on page 178 of the book of Carl Meyer and find the  spanning sets for all the four fundamental subspaces

In [16]:
A_ex = np.array([  [1., 2., 1., 1., 5.], 
                [-2., -4., 0., 4., -2.], 
                [1., 2., 2., 4., 9.]]) 

print("Ex. page 178 4.2.1, \n Matrix A= \n{}".format(A_ex))
print("\n\n")   

U_solEx = rref_withpivot(A_ex)
print("ROW REDUCED form: \n Matrix A=\n {}".format(U_solEx))

Ex. page 178 4.2.1, 
 Matrix A= 
[[ 1.  2.  1.  1.  5.]
 [-2. -4.  0.  4. -2.]
 [ 1.  2.  2.  4.  9.]]



ROW REDUCED form: 
 Matrix A=
 (array([[ 1.,  2.,  0., -2.,  1.],
       [ 0.,  0.,  1.,  3.,  4.],
       [ 0.,  0.,  0.,  0.,  0.]]), array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]]))
